drop table person if exists;

create table USERS (ID_CON bigint generated by default as identity (start with 1), 
NAME varchar(255), SURNAME varchar(255), IDENTIFICATION varchar(255), SEX varchar(255), 
AGE int, primary key (ID_CON));

create table PROFILE (ID_PRO smallint generated by default as identity (start with 1), 
NAME SET("consumidor","vendedor","inspector","administrador"), primary key (ID_PRO));

create table COMPANY (ID_COM bigint generated by default as identity (start with 1), 
IDENTIFICATION varchar(255), NAME varchar(255), ADDRESS varchar(255), PHONE numeric, 
RETURN_PERIOD date, primary key (ID_COM));